version: '2'
services:
    mysql:
      image: mysql:5
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - db:/var/lib/mysql
      ports:
        - 3306:3306
    php:
      build:
        context: ./php
      volumes:
        - html:/var/www/html
      depends_on:
        - mysql
      ports:
      - 8081:8081
    tomcat:
      build:
        context: ./tomcat
      volumes:
        - webapps:/usr/local/tomcat/webapps
      depends_on:
        - mysql
      ports:
      - 8080:8080
volumes:
    db:
    html:
    webapps:
